import { AuthUserProvider } from "@luna/context/auth-user-context";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { AuthRouteHandler } from "./_components/auth-route-handler";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthUserProvider>
          <AuthRouteHandler>{children}</AuthRouteHandler>
        </AuthUserProvider>
      </body>
    </html>
  );
}
